---
blank_issues_enabled: true
contact_links:
  - name: Swift Documentation Forums
    url: "https://forums.swift.org/c/development/swift-docc/80"
    about: "Discuss documentation content or propose major additions"
