---
name: "Content Proposal"
description: "Propose new documentation topics or articles"
labels: ["content proposal"]
body:
  - type: markdown
    attributes:
      value: |
        For significant new content, consider starting
        a discussion on the
        [Swift Forums][1] first.

        [1]: https://forums.swift.org/c/development/swift-docc/80

  - type: textarea
    id: description
    attributes:
      label: "What documentation is needed?"
      description: >-
        Describe the topic and who would benefit
    validations:
      required: true
