#!/usr/bin/env python3
##===----------------------------------------------------------------------===##
##
## This source file is part of the Swift.org open source project
##
## Copyright (c) 2026 Apple Inc. and the Swift.org project authors
## Licensed under Apache License v2.0
##
## See LICENSE.txt for license information
## See CONTRIBUTORS.txt for the list of Swift.org project authors
##
## SPDX-License-Identifier: Apache-2.0
##
##===----------------------------------------------------------------------===##
"""
inject_canonical_link.py — Stamp a `<link rel="canonical">` tag into every
per-route index.html stub of a `docc process-archive
transform-for-static-hosting`-transformed archive.

DocC's static-hosting output is a single-page app: every route gets its own
index.html stub (regenerated by the transform-for-static-hosting step, one
per route, sharing an otherwise-identical <head>), and the real per-page
content is client-rendered from JSON under data/. None of those stubs carry
any page-identifying metadata today, so replicated builds of the same
content (versioned copies, mirrors) have nothing telling search engines
which copy is authoritative — they risk being treated as duplicate/spam
content and de-indexed.

This walks every index.html under an archive root and inserts a
self-describing canonical link whose target is always rooted at a single
fixed `canonical_base_url` (e.g. "https://docs.swift.org/latest"),
regardless of which version_slug actually produced this archive — every
build is expected to declare the same "latest" copy as canonical.

Idempotent: re-running with the same base URL is a no-op, and re-running
with a different one replaces the existing tag in place rather than adding
a second one — so this can be re-run safely if the canonical target ever
changes.

Usage:
    ./inject_canonical_link.py path/to/archive.doccarchive https://docs.swift.org/latest
"""

import html
import os
import re
import sys
from pathlib import Path

CANONICAL_LINK_RE = re.compile(r'<link rel="canonical" href="[^"]*">')


def _route_for(index_html_path, archive_root):
    """Return the route (POSIX, no leading/trailing slash) for a stub's
    directory, relative to the archive root. The root stub's own route is "".
    """
    route_dir = index_html_path.parent.relative_to(archive_root)
    return route_dir.as_posix() if route_dir != Path(".") else ""


def canonicalize_archive(archive_path, canonical_base_url):
    """Insert or replace a self-describing `<link rel="canonical">` tag in
    every index.html stub under `archive_path`, pointed at the equivalent
    route under `canonical_base_url`.

    Returns (files_scanned, files_modified). Raises ValueError if
    archive_path doesn't look like a transformed .doccarchive (missing a
    root index.html).
    """
    archive = Path(archive_path)
    root_index = archive / "index.html"
    if not root_index.is_file():
        raise ValueError(
            f"{os.fspath(archive)!r} does not look like a transformed "
            f".doccarchive (missing root index.html)"
        )

    base = canonical_base_url.rstrip("/")

    files_scanned = 0
    files_modified = 0

    for index_path in archive.rglob("index.html"):
        files_scanned += 1
        route = _route_for(index_path, archive)
        canonical_url = f"{base}/{route}" if route else base
        new_tag = (
            f'<link rel="canonical" href="{html.escape(canonical_url, quote=True)}">'
        )

        text = index_path.read_text()
        if CANONICAL_LINK_RE.search(text):
            new_text = CANONICAL_LINK_RE.sub(new_tag, text, count=1)
        elif "</head>" in text:
            new_text = text.replace("</head>", new_tag + "</head>", 1)
        else:
            continue

        if new_text != text:
            index_path.write_text(new_text)
            files_modified += 1

    return files_scanned, files_modified


def main():
    if len(sys.argv) != 3:
        sys.stderr.write(
            f"usage: {sys.argv[0]} <path-to-doccarchive> <canonical-base-url>\n"
        )
        sys.exit(2)

    archive = os.path.abspath(sys.argv[1])
    canonical_base_url = sys.argv[2]
    try:
        files_scanned, files_modified = canonicalize_archive(archive, canonical_base_url)
    except ValueError as e:
        sys.stderr.write(f"error: {e}\n")
        sys.exit(1)

    print(f"scanned {files_scanned} files; modified {files_modified}")


if __name__ == "__main__":
    main()
