name: Pull request

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  soundness:
    name: Soundness
    uses: swiftlang/github-workflows/.github/workflows/soundness.yml@0.0.9
    with:
      api_breakage_check_enabled: false
      docs_check_enabled: false
      format_check_enabled: false
      license_header_check_enabled: true
      python_lint_check_enabled: false
      unacceptable_language_check_enabled: true
      broken_symlink_check_enabled: true
      shell_check_enabled: true
      yamllint_check_enabled: true
